os: linux
dist: xenial

language: r

r_packages: devtools

services: docker

env:
  global:
  - REPO=kguidonimartins/vbpflow-app

warnings_are_errors: false

before_install: |
  sudo apt-get -y install \
  build-essential \
  libcurl4-gnutls-dev \
  libxml2-dev \
  libssl-dev \
  libgdal-dev \
  bwidget \
  libgdal1-dev \
  libgeos-dev \
  libgeos++-dev \
  libgsl0-dev \
  libproj-dev \
  libspatialite-dev \
  netcdf-bin \
  libudunits2-dev

cache: packages

script: make all

jobs:
  include:
  - r: release

after_success:
  - Rscript -e 'devtools::install()'
  - docker login -u kguidonimartins -p "$DOCKER_PASSWORD"
  - export REPO=kguidonimartins/vbpflow-app
  - export TAG=`if [ "$TRAVIS_BRANCH" == "trunk" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
