os:
  - linux

language: r

r_packages:
  - devtools

sudo: false

before_install: |
  sudo apt-get -y install
  build-essential \
  bwidget \
  libcurl4-gnutls-dev \
  libgdal-dev \
  libgdal1-dev \
  libgeos++-dev \
  libgeos-dev \
  libgsl0-dev \
  libproj-dev \
  libspatialite-dev \
  libssl-dev \
  libudunits2-dev
  libxml2-dev \
  netcdf-bin \

cache: packages

script: make check

matrix:
  include:
  - r: release

after_success:
  - Rscript -e 'devtools::install()'

