os: linux

language: R

r_packages: devtools

sudo: false

services: docker

before_install: |
  sudo apt-get -y install \
  build-essential \
  libcurl4-gnutls-dev \
  libxml2-dev \
  libssl-dev \
  libgdal-dev \
  bwidget \
  libgdal1-dev \
  libgeos-dev \
  libgeos++-dev \
  libgsl0-dev \
  libproj-dev \
  libspatialite-dev \
  netcdf-bin \
  libudunits2-dev

cache: packages

script: make all

matrix:
  include:
  - r: release

after_success:
  - Rscript -e 'devtools::install()'
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - export DOCKER_IMAGE=kguidonimartins/vbpflow-app
  - export TAG=`if [ "$TRAVIS_BRANCH" == "trunk" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $DOCKER_IMAGE:$COMMIT .
  - docker tag $DOCKER_IMAGE:$COMMIT $DOCKER_IMAGE:$TAG
  - docker tag $DOCKER_IMAGE:$COMMIT $DOCKER_IMAGE:travis-$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_IMAGE
