app <- ShinyDriver$new("../")
app$snapshotInit("test-shinyapp-session")

app$setInputs(origin = character(0))
app$setInputs(origin = "Brazil")
app$setInputs(destination = character(0))
app$setInputs(destination = "China")
app$setInputs(destination = c("China", "Japan"))
app$setInputs(destination = c("China", "Japan", "Italy"))
app$setInputs(year = "2004")
app$setInputs(colormap = "HDI")
app$snapshotDownload("download_map")
app$setInputs(make_plot = "click")
app$snapshot()
