context("Testing `distinct_input_select_countries()`")

# df <- read_vp_flow_data()

pkg_data <- 
  system.file("extdata", "virtual-pollinators-flow.qs", package="vbpflow")

df <- 
  qread(pkg_data) %>%
  filter(item_code != 0) %>%
  .[.$reporter_countries != .$partner_countries, ]

# gxs_selection("distinct_input_select_countries(df, reporter_countries)")

## Testing 'distinct_input_select_countries(df, reporter_c...'              ####
## Initially generated by xpectr
xpectr::set_test_seed(42)
# Assigning output
output_19370 <- distinct_input_select_countries(df, reporter_countries)
# Testing class
expect_equal(
  class(output_19370),
  "character",
  fixed = TRUE)
# Testing type
expect_type(
  output_19370,
  type = "character")
# Testing values
expect_equal(
  xpectr::smpl(output_19370, n = 30),
  c("Bangladesh", "Benin", "Bolivia", "Bosnia and Herzegovina", "Cuba", 
    "Estonia", "Gambia", "Guatemala", "Iran", "Ireland", "Israel", 
    "Kyrgyzstan", "Latvia", "Nepal", "Oman", "Pakistan", "Paraguay", 
    "Poland", "Saint Lucia", "Seychelles", "Slovenia", "Solomon Islands", 
    "Suriname", "Swaziland", "Sweden", "Taiwan", "Trinidad and Tobago", 
    "Uganda", "Vanuatu", "Zimbabwe"),
  fixed = TRUE)
# Testing names
expect_equal(
  names(xpectr::smpl(output_19370, n = 30)),
  NULL,
  fixed = TRUE)
# Testing length
expect_equal(
  length(output_19370),
  170L)
# Testing sum of element lengths
expect_equal(
  sum(xpectr::element_lengths(output_19370)),
  170L)
## Finished testing 'distinct_input_select_countries(df, reporter_c...'     ####
