pkg_data <- 
  system.file("extdata", "virtual-pollinators-flow.qs", package="vbpflow")

vp_flow_data <- 
  qread(pkg_data) %>%
  filter(item_code != 0) %>%
  .[.$reporter_countries != .$partner_countries, ]

# gxs_selection("vp_flow_data")

## Testing 'vp_flow_data'                                                   ####
## Initially generated by xpectr
xpectr::set_test_seed(42)
# Testing class
expect_equal(
  class(vp_flow_data),
  c("spec_tbl_df", "tbl_df", "tbl", "data.frame"),
  fixed = TRUE)
# Testing column values
expect_equal(
  xpectr::smpl(vp_flow_data[["reporter_country_code"]], n = 30),
  c(255, 27, 33, 33, 63, 68, 100, 106, 106, 106, 106, 121, 126, 143,
157, 165, 117, 185, 272, 203, 38, 226, 226, 230, 229, 229, 229,
229, 231, 231),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(vp_flow_data[["reporter_countries"]], n = 30),
  c("Belgium", "Bulgaria", "Canada", "Canada", "Estonia", "France", 
    "India", "Italy", "Italy", "Italy", "Italy", "Lebanon", "Lithuania", 
    "Morocco", "Nicaragua", "Pakistan", "South Korea", "Russia", 
    "Republic of Serbia", "Spain", "Sri Lanka", "Uganda", "Uganda", 
    "Ukraine", "United Kingdom", "United Kingdom", "United Kingdom", 
    "United Kingdom", "United States of America", "United States of America"),
  fixed = TRUE)
expect_equal(
  xpectr::smpl(vp_flow_data[["item_code"]], n = 30),
  c(388, 521, 515, 592, 397, 89, 292, 176, 507, 567, 268, 568, 388,
388, 289, 495, 544, 572, 521, 495, 490, 692, 661, 89, 181, 244,
244, 290, 266, 252),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(vp_flow_data[["element"]], n = 30),
  c("Export Quantity", "Export Quantity", "Export Quantity", "Export Quantity", 
    "Export Quantity", "Export Quantity", "Export Quantity", "Export Quantity", 
    "Export Quantity", "Export Quantity", "Export Quantity", "Export Quantity", 
    "Export Quantity", "Export Quantity", "Export Quantity", "Export Quantity", 
    "Export Quantity", "Export Quantity", "Export Quantity", "Export Quantity", 
    "Export Quantity", "Export Quantity", "Export Quantity", "Export Quantity", 
    "Export Quantity", "Export Quantity", "Export Quantity", "Export Quantity", 
    "Export Quantity", "Export Quantity"),
  fixed = TRUE)
expect_equal(
  xpectr::smpl(vp_flow_data[["partner_country_code"]], n = 30),
  c(250, 252, 194, 190, 126, 203, 114, 104, 54, 256, 173, 13, 185,
68, 138, 231, 214, 235, 80, 173, 229, 33, 211, 166, 11, 162,
104, 54, 40, 22),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(vp_flow_data[["partner_countries"]], n = 30),
  c("Democratic Republic of the Congo", "Unspecified Area", "Saudi Arabia", 
    "Saint Pierre and Miquelon", "Lithuania", "Spain", "Kenya", 
    "Ireland", "Denmark", "Luxembourg", "Poland", "Bahrain", "Russia", 
    "France", "Mexico", "United States of America", "Taiwan", "Uzbekistan", 
    "Bosnia and Herzegovina", "Poland", "United Kingdom", "Canada", 
    "Switzerland", "Panama", "Austria", "Norway", "Ireland", "Denmark", 
    "Chile", "Aruba"),
  fixed = TRUE)
expect_equal(
  xpectr::smpl(vp_flow_data[["item"]], n = 30),
  c("Tomatoes", "Pears", "Apples", "Kiwi fruit", "Cucumbers and gherkins", 
    "Buckwheat", "Mustard seed", "Beans, dry", "Grapefruit (inc. pomelos)", 
    "Watermelons", "Oil, sunflower", "Melons, other (inc.cantaloupes)", 
    "Tomatoes", "Tomatoes", "Sesame seed", "Tangerines, mandarins, clementines, satsumas", 
    "Strawberries", "Avocados", "Pears", "Tangerines, mandarins, clementines, satsumas", 
    "Oranges", "Vanilla", "Cocoa, beans", "Buckwheat", "Broad beans, horse beans, dry", 
    "Oil, groundnut", "Oil, groundnut", "Oil, sesame", "Oil, castor beans", 
    "Oil, coconut (copra)"),
  fixed = TRUE)
expect_equal(
  xpectr::smpl(vp_flow_data[["year"]], n = 30),
  c(2011, 2006, 2004, 2008, 2015, 2009, 2002, 2003, 2008, 2009, 2014,
2012, 2006, 2010, 2006, 2009, 2008, 2002, 2014, 2015, 2012,
2002, 2010, 2012, 2007, 2008, 2010, 2014, 2011, 2015),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(vp_flow_data[["traded_t"]], n = 30),
  c(3, 2, 104, 0, 271, 1, 14, 1, 12, 12, 256, 4, 10937, 281837, 205,
58, 11, 0, 11, 113309, 1, 5, 2435, 0, 0, 18, 29, 7, 39, 19),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(vp_flow_data[["adj_traded_t"]], n = 30),
  c(3, 2, 104, 0, 271, 1, 14, 1, 12, 12, 568.88889, 4, 10937, 281837,
205, 58, 11, 0, 11, 113309, 1, 5, 2435, 0, 0, 40.90909, 65.90909,
11.66667, 80.91286, 82.6087),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(vp_flow_data[["dependence_rate"]], n = 30),
  c(0.05, 0.65, 0.65, 0.95, 0.65, 0.65, 0.25, 0.25, 0.05, 0.95, 0.25,
0.95, 0.05, 0.05, 0.25, 0.05, 0.25, 0.65, 0.65, 0.05, 0.05,
0.95, 0.95, 0.65, 0.25, 0.05, 0.05, 0.25, 0.65, 0.25),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(vp_flow_data[["potential_poll_trade"]], n = 30),
  c(0.15, 1.3, 67.6, 0, 176.15, 0.65, 3.5, 0.25, 0.6, 11.4, 142.22222,
3.8, 546.85, 14091.85, 51.25, 2.9, 2.75, 0, 7.15, 5665.45, 0.05,
4.75, 2313.25, 0, 0, 2.04545, 3.29545, 2.91667, 52.59336, 20.65217),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(vp_flow_data[["poll_provision"]], n = 30),
  c(0.2508, 0.21104, 0.13429, 0.13793, 0.66337, 0.23708, 0.12052,
0.23352, 0.23186, 0.23255, 0.2364, 0.43177, 0.40166, 0.17097,
0.57758, 0.18105, 0.58348, 0.20432, 0.15773, 0.35409, 0.54698,
0.20567, 0.20457, 0.11696, 0.28927, 0.28796, 0.28154, 0.28658,
0.25129, 0.25807),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(vp_flow_data[["vp_flow"]], n = 30),
  c(0.03762, 0.27435, 9.07816, 0, 116.85266, 0.1541, 0.42184, 0.05838,
0.13912, 2.65101, 33.62071, 1.64071, 219.6504, 2409.25881, 29.60075,
0.52505, 1.60458, 0, 1.12776, 2006.10284, 0.02735, 0.97694,
473.21659, 0, 0, 0.58902, 0.9278, 0.83585, 13.21602, 5.3297),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(vp_flow_data[["reporter_long"]], n = 30),
  c(4.64065, 25.21553, -98.30777, -98.30777, 25.54249, -2.76173, 79.61198,
12.07001, 12.07001, 12.07001, 12.07001, 35.88016, 23.88719,
-8.45616, -85.03053, 69.33958, 127.83916, 96.68656, 20.78958,
-3.64755, 80.70108, 32.36908, 32.36908, 31.38326, -2.86563,
-2.86563, -2.86563, -2.86563, -112.46167, -112.46167),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(vp_flow_data[["reporter_lat"]], n = 30),
  c(50.63982, 42.7689, 61.36206, 61.36206, 58.67193, 42.17344, 22.88578,
42.79663, 42.79663, 42.79663, 42.79663, 33.92307, 55.32611,
29.83763, 12.84709, 29.94975, 36.38524, 61.98052, 44.2215, 40.24449,
7.61267, 1.27469, 1.27469, 48.99657, 54.12387, 54.12387, 54.12387,
54.12387, 45.67955, 45.67955),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(vp_flow_data[["partner_long"]], n = 30),
  c(23.64396, NA, 44.53686, -56.3032, 23.88719, -3.64755, 37.79594,
-8.13794, 10.02801, 6.07182, 19.39013, 50.54197, 96.68656, -2.76173,
-102.52345, -112.46167, 120.95427, 63.14002, 17.76877, 19.39013,
-2.86563, -98.30777, 8.20867, -80.11915, 14.12648, 15.34835,
-8.13794, 10.02801, -71.38256, -69.98268),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(vp_flow_data[["partner_lat"]], n = 30),
  c(-2.87746, NA, 24.12246, 46.91919, 55.32611, 40.24449, 0.59988,
53.17545, 55.98125, 49.76725, 52.1276, 26.04205, 61.98052, 42.17344,
23.94754, 45.67955, 23.75399, 41.75554, 44.1745, 52.1276, 54.12387,
61.36206, 46.79786, 8.51751, 47.58549, 68.75016, 53.17545, 55.98125,
-37.73071, 12.52088),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(vp_flow_data[["reporter_hdi"]], n = 30),
  c(0.8964, 0.76613, 0.8976, 0.8976, 0.8356, 0.87527, 0.5626, 0.86293,
0.86293, 0.86293, 0.86293, 0.74864, 0.81747, 0.60167, 0.6128,
0.511, 0.868, 0.7706, 0, 0.85567, 0.733, 0.4632, 0.4632, 0.72333,
0.89533, 0.89533, 0.89533, 0.89533, 0.90607, 0.90607),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(vp_flow_data[["partner_hdi"]], n = 30),
  c(0.3886, 0, 0.79653, 0, 0.81747, 0.85567, 0.51967, 0.8994, 0.90793,
0.8826, 0.82307, 0.79873, 0.7706, 0.87527, 0.7386, 0.90607,
0, 0.65147, 0.7152, 0.82307, 0.89533, 0.8976, 0.9182, 0.75273,
0.8758, 0.93607, 0.8994, 0.90793, 0.80093, 0),
  tolerance = 1e-4)
# Testing column names
expect_equal(
  names(vp_flow_data),
  c("reporter_country_code", "reporter_countries", "item_code", "element", 
    "partner_country_code", "partner_countries", "item", "year", 
    "traded_t", "adj_traded_t", "dependence_rate", "potential_poll_trade", 
    "poll_provision", "vp_flow", "reporter_long", "reporter_lat", 
    "partner_long", "partner_lat", "reporter_hdi", "partner_hdi"),
  fixed = TRUE)
# Testing column classes
expect_equal(
  xpectr::element_classes(vp_flow_data),
  c("numeric", "character", "numeric", "character", "numeric", "character", 
    "character", "numeric", "numeric", "numeric", "numeric", "numeric", 
    "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", 
    "numeric", "numeric"),
  fixed = TRUE)
# Testing column types
expect_equal(
  xpectr::element_types(vp_flow_data),
  c("double", "character", "double", "character", "double", "character", 
    "character", "double", "double", "double", "double", "double", 
    "double", "double", "double", "double", "double", "double", 
    "double", "double"),
  fixed = TRUE)
# Testing dimensions
expect_equal(
  dim(vp_flow_data),
  c(718125L, 20L))
# Testing group keys
expect_equal(
  colnames(dplyr::group_keys(vp_flow_data)),
  character(0),
  fixed = TRUE)
## Finished testing 'vp_flow_data'                                          ####
