context("Testing `summarise_vp_flow_all_years()`")

pkg_data <-
  system.file("extdata", "virtual-pollinators-flow.qs", package = "vbpflow")

df <-
  qread(pkg_data) %>%
  .[.$reporter_countries != .$partner_countries, ]

# xpectr::gxs_selection("summarise_vp_flow_all_years(df)")

## Testing 'summarise_vp_flow_all_years(df)'                                ####
## Initially generated by xpectr
xpectr::set_test_seed(42)
# Assigning output
output_19148 <- summarise_vp_flow_all_years(df)
# Testing class
expect_equal(
  class(output_19148),
  c("tbl_df", "tbl", "data.frame"),
  fixed = TRUE
)
# Testing column values
expect_equal(
  xpectr::smpl(output_19148[["reporter_countries"]], n = 30),
  c(
    "Ukraine", "Estonia", "Saint Lucia", "Iran", "Cambodia", "United Arab Emirates",
    "Bulgaria", "Pakistan", "Moldova", "Cameroon", "United Republic of Tanzania",
    "Denmark", "Argentina", "Canada", "Ukraine", "Belgium", "Malaysia",
    "United Republic of Tanzania", "Switzerland", "Zambia", "Philippines",
    "India", "Hong Kong S.A.R.", "South Africa", "Pakistan", "Bolivia",
    "Russia", "Ghana", "New Zealand", "Italy"
  ),
  fixed = TRUE
)
expect_equal(
  xpectr::smpl(output_19148[["partner_countries"]], n = 30),
  c(
    "Ireland", "Marshall Islands", "Grenada", "Central African Republic",
    "Hong Kong S.A.R.", "Sri Lanka", "Dominican Republic", "South Africa",
    "Latvia", "Romania", "Lithuania", "Mauritania", "Guinea", "Slovakia",
    "Turkmenistan", "Brazil", "Uruguay", "Israel", "United States of America",
    "Democratic Republic of the Congo", "India", "Russia", "Macao S.A.R",
    "Ireland", "Unspecified Area", "United Kingdom", "Algeria",
    "Spain", "Netherlands", "Poland"
  ),
  fixed = TRUE
)
expect_equal(
  xpectr::smpl(output_19148[["reporter_long"]], n = 30),
  c(
    31.38326, 25.54249, -60.9697, 54.27407, 104.90694, 54.30017, 25.21553,
    69.33958, 28.45673, 12.73964, 34.8131, 10.02801, -65.17981,
    -98.30777, 31.38326, 4.64065, 109.69762, 34.8131, 8.20867, 27.77476,
    122.88393, 79.61198, 114.1138, 25.0839, 69.33958, -64.68539,
    96.68656, -1.21677, 171.48492, 12.07001
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["reporter_lat"]], n = 30),
  c(
    48.99657, 58.67193, 13.89479, 32.57503, 12.72005, 23.90528, 42.7689,
    29.94975, 47.19499, 5.6911, -6.27565, 55.98125, -35.38135, 61.36206,
    48.99657, 50.63982, 3.78987, -6.27565, 46.79786, -13.45824,
    11.77537, 22.88578, 22.39828, -29.00034, 29.94975, -16.70815,
    61.98052, 7.95346, -41.81114, 42.79663
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["reporter_hdi"]], n = 30),
  c(
    0.72333, 0.8356, 0.71593, 0.73693, 0.51407, 0.83293, 0.76613,
    0.511, 0.66, 0.4938, 0.47053, 0.90793, 0.7978, 0.8976, 0.72333,
    0.8964, 0.7572, 0.47053, 0.9182, 0.5166, 0.66013, 0.5626, 0.88707,
    0.6402, 0.511, 0.6422, 0.7706, 0.53547, 0.89507, 0.86293
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["partner_long"]], n = 30),
  c(
    -8.13794, 170.33976, -61.6822, 20.46827, 114.1138, 80.70108, -70.50569,
    25.0839, 24.91236, 24.97293, 23.88719, -10.3478, -10.94067,
    19.47905, 59.371, -53.09783, -56.01807, 35.00445, -112.46167,
    23.64396, 79.61198, 96.68656, 113.50932, -8.13794, NA, -2.86563,
    2.61732, -3.64755, 5.28145, 19.39013
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["partner_lat"]], n = 30),
  c(
    53.17545, 7.00376, 12.11725, 6.56823, 22.39828, 7.61267, 18.89433,
    -29.00034, 56.85085, 45.85243, 55.32611, 20.25737, 10.43622,
    48.70548, 39.11554, -10.78778, -32.79952, 31.4611, 45.67955,
    -2.87746, 22.88578, 61.98052, 22.22312, 53.17545, NA, 54.12387,
    28.15894, 40.24449, 52.10079, 52.1276
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["partner_hdi"]], n = 30),
  c(
    0.8994, 0, 0.73679, 0.3352, 0.88707, 0.733, 0.69173, 0.6402, 0.8072,
    0.77413, 0.81747, 0.47947, 0.39213, 0.81347, 0.68817, 0.71827,
    0.77087, 0.8806, 0.90607, 0.3886, 0.5626, 0.7706, 0, 0.8994,
    0, 0.89533, 0.70973, 0.85567, 0.90367, 0.82307
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["vp_flow"]], n = 30),
  c(
    0.78373, 1.50258, 2, 2.14102, 9.69564, 13.652, 39.39205, 72.85728,
    82.06866, 86.4059, 99.98094, 155.33664, 167.894, 271.94802,
    700.46909, 827.95419, 1482.22218, 1789.86529, 2289.00961, 9247.0956,
    10044.00301, 36490.19352, 37652.04787, 49112.6956, 78906.38717,
    85033.96324, 87995.33806, 104669.29459, 362475.05345, 618473.30933
  ),
  tolerance = 1e-4
)
# Testing column names
expect_equal(
  names(output_19148),
  c(
    "reporter_countries", "partner_countries", "reporter_long", "reporter_lat",
    "reporter_hdi", "partner_long", "partner_lat", "partner_hdi",
    "vp_flow"
  ),
  fixed = TRUE
)
# Testing column classes
expect_equal(
  xpectr::element_classes(output_19148),
  c(
    "character", "character", "numeric", "numeric", "numeric", "numeric",
    "numeric", "numeric", "numeric"
  ),
  fixed = TRUE
)
# Testing column types
expect_equal(
  xpectr::element_types(output_19148),
  c(
    "character", "character", "double", "double", "double", "double",
    "double", "double", "double"
  ),
  fixed = TRUE
)
# Testing dimensions
expect_equal(
  dim(output_19148),
  c(11505L, 9L)
)
# Testing group keys
expect_equal(
  colnames(dplyr::group_keys(output_19148)),
  character(0),
  fixed = TRUE
)
## Finished testing 'summarise_vp_flow_all_years(df)'                       ####
