# df <- read_vp_flow_data()

pkg_data <- 
  system.file("extdata", "virtual-pollinators-flow.qs", package="vbpflow")

df <- 
  qread(pkg_data) %>%
  filter(item_code != 0) %>%
  .[.$reporter_countries != .$partner_countries, ]

# gxs_selection("distinct_countries(df)")

## Testing 'distinct_countries(df)'                                         ####
## Initially generated by xpectr
xpectr::set_test_seed(42)
# Assigning output
output_19148 <- distinct_countries(df)
# Testing class
expect_equal(
  class(output_19148),
  c("tbl_df", "tbl", "data.frame"),
  fixed = TRUE)
# Testing column values
expect_equal(
  xpectr::smpl(output_19148[["reporter_countries"]], n = 30),
  c("Italy", "Canada", "India", "Peru", "Colombia", "Italy", "India", 
    "Denmark", "Senegal", "Bosnia and Herzegovina", "Sweden", "South Africa", 
    "Macedonia", "United States of America", "Israel", "Burkina Faso", 
    "Portugal", "South Africa", "Honduras", "Italy", "South Africa", 
    "Philippines", "Greece", "Netherlands", "Ivory Coast", "Singapore", 
    "Germany", "Brazil", "Malaysia", "Bolivia"),
  fixed = TRUE)
expect_equal(
  xpectr::smpl(output_19148[["partner_countries"]], n = 30),
  c("Angola", "Saint Pierre and Miquelon", "Slovakia", "Luxembourg", 
    "Indonesia", "Vietnam", "Republic of Serbia", "Senegal", "Saudi Arabia", 
    "Cyprus", "Latvia", "Morocco", "Switzerland", "Cayman Islands", 
    "Canada", "Benin", "Colombia", "Uganda", "Finland", "United States of America", 
    "Zimbabwe", "Hong Kong S.A.R.", "Egypt", "Portugal", "Mali", 
    "Malaysia", "Tunisia", "Israel", "South Korea", "Colombia"),
  fixed = TRUE)
expect_equal(
  xpectr::smpl(output_19148[["reporter_long"]], n = 30),
  c(12.07001, -98.30777, 79.61198, -74.38243, -73.08115, 12.07001,
79.61198, 10.02801, -14.47349, 17.76877, 16.74558, 25.0839,
21.68211, -112.46167, 35.00445, -1.75457, -8.50104, 25.0839,
-86.61517, 12.07001, 25.0839, 122.88393, 22.95556, 5.28145,
-5.56922, 103.81726, 10.38578, -53.09783, 109.69762, -64.68539),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(output_19148[["reporter_lat"]], n = 30),
  c(42.79663, 61.36206, 22.88578, -9.1528, 3.91383, 42.79663, 22.88578,
55.98125, 14.36624, 44.1745, 62.77967, -29.00034, 41.59531,
45.67955, 31.4611, 12.26954, 39.59551, -29.00034, 14.82688,
42.79663, -29.00034, 11.77537, 39.0747, 52.10079, 7.62843, 1.35876,
51.10698, -10.78778, 3.78987, -16.70815),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(output_19148[["reporter_hdi"]], n = 30),
  c(0.86293, 0.8976, 0.5626, 0.7118, 0.70193, 0.86293, 0.5626, 0.90793,
0.4436, 0.7152, 0.90613, 0.6402, 0.71793, 0.90607, 0.8806, 0.35313,
0.81427, 0.6402, 0.58713, 0.86293, 0.6402, 0.66013, 0.84613,
0.90367, 0.43147, 0.8828, 0.91167, 0.71827, 0.7572, 0.6422),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(output_19148[["partner_long"]], n = 30),
  c(17.53737, -56.3032, 19.47905, 6.07182, 117.24011, 106.29915, 20.78958,
-14.47349, 44.53686, 33.006, 24.91236, -8.45616, 8.20867, -80.91213,
-98.30777, 2.32785, -73.08115, 32.36908, 26.27467, -112.46167,
29.85144, 114.1138, 29.8619, -8.50104, -3.54269, 109.69762,
9.55288, 35.00445, 127.83916, -73.08115),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(output_19148[["partner_lat"]], n = 30),
  c(-12.29336, 46.91919, 48.70548, 49.76725, -2.21505, 16.64602, 44.2215,
14.36624, 24.12246, 34.91667, 56.85085, 29.83763, 46.79786,
19.42896, 61.36206, 9.64176, 3.91383, 1.27469, 64.49885, 45.67955,
-19.0042, 22.39828, 26.49593, 39.59551, 17.34582, 3.78987, 34.11956,
31.4611, 36.38524, 3.91383),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(output_19148[["partner_hdi"]], n = 30),
  c(0.49467, 0, 0.81347, 0.8826, 0.65033, 0.63933, 0, 0.4436, 0.79653,
0.8414, 0.8072, 0.60167, 0.9182, 0, 0.8976, 0.461, 0.70193,
0.4632, 0.8966, 0.90607, 0.46327, 0.88707, 0.6528, 0.81427,
0.37967, 0.7572, 0.70087, 0.8806, 0.868, 0.70193),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(output_19148[["year"]], n = 30),
  c(2009, 2015, 2009, 2015, 2008, 2009, 2014, 2003, 2007, 2013, 2007,
2012, 2003, 2014, 2015, 2003, 2015, 2014, 2012, 2003, 2007,
2007, 2012, 2012, 2011, 2010, 2011, 2011, 2014, 2009),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(output_19148[["vp_flow"]], n = 30),
  c(0.58136, 1.08081, 1.4459, 1.54157, 6.25636, 8.51115, 22.3445,
38.04329, 42.09736, 44.02656, 49.31252, 70.91155, 74.28799,
108.98968, 235.58515, 274.73612, 461.86062, 537.95788, 654.44494,
1964.91662, 2104.98718, 5581.24117, 5723.08592, 6927.46856,
10751.96569, 11382.2476, 12163.41983, 14494.38492, 39953.85703,
78098.5757),
  tolerance = 1e-4)
# Testing column names
expect_equal(
  names(output_19148),
  c("reporter_countries", "partner_countries", "reporter_long", "reporter_lat", 
    "reporter_hdi", "partner_long", "partner_lat", "partner_hdi", 
    "year", "vp_flow"),
  fixed = TRUE)
# Testing column classes
expect_equal(
  xpectr::element_classes(output_19148),
  c("character", "character", "numeric", "numeric", "numeric", "numeric", 
    "numeric", "numeric", "numeric", "numeric"),
  fixed = TRUE)
# Testing column types
expect_equal(
  xpectr::element_types(output_19148),
  c("character", "character", "double", "double", "double", "double", 
    "double", "double", "double", "double"),
  fixed = TRUE)
# Testing dimensions
expect_equal(
  dim(output_19148),
  c(89923L, 10L))
# Testing group keys
expect_equal(
  colnames(dplyr::group_keys(output_19148)),
  character(0),
  fixed = TRUE)
## Finished testing 'distinct_countries(df)'                                ####
