# df <- read_vp_flow_data()

pkg_data <- 
  system.file("extdata/virtual-pollinators-flow.qs", package="vbpflow")

df <- 
  qread(pkg_data) %>%
  filter(item_code != 0) %>%
  .[.$reporter_countries != .$partner_countries, ]


# gxs_selection("min_max_vp_flow_by_input_year(df, 2001)")

## Testing 'min_max_vp_flow_by_input_year(df, 2001)'                        ####
## Initially generated by xpectr
xpectr::set_test_seed(42)
# Assigning output
output_19370 <- min_max_vp_flow_by_input_year(df, 2001)
# Testing class
expect_equal(
  class(output_19370),
  c("tbl_df", "tbl", "data.frame"),
  fixed = TRUE)
# Testing column values
expect_equal(
  output_19370[["year"]],
  2001,
  tolerance = 1e-4)
expect_equal(
  output_19370[["vp_flow_min"]],
  0.00622,
  tolerance = 1e-4)
expect_equal(
  output_19370[["vp_flow_max"]],
  671568.65738,
  tolerance = 1e-4)
# Testing column names
expect_equal(
  names(output_19370),
  c("year", "vp_flow_min", "vp_flow_max"),
  fixed = TRUE)
# Testing column classes
expect_equal(
  xpectr::element_classes(output_19370),
  c("numeric", "numeric", "numeric"),
  fixed = TRUE)
# Testing column types
expect_equal(
  xpectr::element_types(output_19370),
  c("double", "double", "double"),
  fixed = TRUE)
# Testing dimensions
expect_equal(
  dim(output_19370),
  c(1L, 3L))
# Testing group keys
expect_equal(
  colnames(dplyr::group_keys(output_19370)),
  character(0),
  fixed = TRUE)
## Finished testing 'min_max_vp_flow_by_input_year(df, 2001)'               ####
