context("Testing `no_vp_flow()`")

# gxs_selection("no_vp_flow()")

## Testing 'no_vp_flow()'                                                   ####
## Initially generated by xpectr
xpectr::set_test_seed(42)
# Testing is NULL
expect_true(
  is.null(no_vp_flow())
)
## Finished testing 'no_vp_flow()'                                          ####
