context("Testing `filter_countries_by_input_select_year()`")

pkg_data <-
  system.file("extdata", "virtual-pollinators-flow.qs", package = "vbpflow")

df <-
  qread(pkg_data) %>%
  .[.$reporter_countries != .$partner_countries, ]

# xpectr::gxs_selection("filter_countries_by_input_select_year(df, 2001)")

## Testing 'filter_countries_by_input_select_year(df, 2001)'                ####
## Initially generated by xpectr
xpectr::set_test_seed(42)
# Assigning output
output_19148 <- filter_countries_by_input_select_year(df, 2001)
# Testing class
expect_equal(
  class(output_19148),
  c("spec_tbl_df", "tbl_df", "tbl", "data.frame"),
  fixed = TRUE
)
# Testing column values
expect_equal(
  xpectr::smpl(output_19148[["reporter_countries"]], n = 30),
  c(
    "Belgium", "Bulgaria", "Canada", "Canada", "Egypt", "France",
    "Guatemala", "Indonesia", "Iran", "Iran", "Israel", "Italy",
    "Italy", "Lithuania", "Netherlands", "Netherlands", "Peru",
    "Portugal", "Russia", "Spain", "Spain", "Turkey", "Turkey",
    "United Kingdom", "United Kingdom", "United Republic of Tanzania",
    "United Republic of Tanzania", "United States of America", "United States of America",
    "United States of America"
  ),
  fixed = TRUE
)
expect_equal(
  xpectr::smpl(output_19148[["partner_countries"]], n = 30),
  c(
    "Norway", "Canada", "Japan", "Taiwan", "Kuwait", "Latvia", "Poland",
    "Somalia", "United Arab Emirates", "Afghanistan", "Finland",
    "Croatia", "Russia", "Hungary", "Hong Kong S.A.R.", "Croatia",
    "United States of America", "Brazil", "Unspecified Area", "Poland",
    "United States of America", "Oman", "Ethiopia", "Australia",
    "Jordan", "Germany", "Algeria", "Guatemala", "Israel", "Spain"
  ),
  fixed = TRUE
)
expect_equal(
  xpectr::smpl(output_19148[["year"]], n = 30),
  c(
    2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001,
    2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001,
    2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["vp_flow"]], n = 30),
  c(
    8.3243, 1.72506, 0.71047, 8.8098, 0.01243, 0.18932, 4.84283, 22.37298,
    330.94157, 198.42296, 3.18766, 48.99208, 542.6461, 45.93194,
    30.39562, 2.76357, 22.10943, 395.12107, 0.0287, 76.09733, 5.5836,
    13.87149, 24.74746, 1.90182, 0.12679, 0.46709, 6.80019, 1.51406,
    13.64707, 283.32137
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["reporter_long"]], n = 30),
  c(
    4.64065, 25.21553, -98.30777, -98.30777, 29.8619, -2.76173, -90.36482,
    117.24011, 54.27407, 54.27407, 35.00445, 12.07001, 12.07001,
    23.88719, 5.28145, 5.28145, -74.38243, -8.50104, 96.68656, -3.64755,
    -3.64755, 35.16895, 35.16895, -2.86563, -2.86563, 34.8131, 34.8131,
    -112.46167, -112.46167, -112.46167
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["reporter_lat"]], n = 30),
  c(
    50.63982, 42.7689, 61.36206, 61.36206, 26.49593, 42.17344, 15.69404,
    -2.21505, 32.57503, 32.57503, 31.4611, 42.79663, 42.79663, 55.32611,
    52.10079, 52.10079, -9.1528, 39.59551, 61.98052, 40.24449, 40.24449,
    39.0616, 39.0616, 54.12387, 54.12387, -6.27565, -6.27565, 45.67955,
    45.67955, 45.67955
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["partner_long"]], n = 30),
  c(
    15.34835, -98.30777, 138.0309, 120.95427, 47.587, 24.91236, 19.39013,
    45.70714, 54.30017, 66.00473, 26.27467, 16.40413, 96.68656,
    19.39559, 114.1138, 16.40413, -112.46167, -53.09783, NA, 19.39013,
    -112.46167, 56.09166, 39.6008, 134.491, 36.77136, 10.38578,
    2.61732, -90.36482, 35.00445, -3.64755
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["partner_lat"]], n = 30),
  c(
    68.75016, 61.36206, 37.5923, 23.75399, 29.33431, 56.85085, 52.1276,
    4.75063, 23.90528, 33.83523, 64.49885, 45.08048, 61.98052, 47.16278,
    22.39828, 45.08048, 45.67955, -10.78778, NA, 52.1276, 45.67955,
    20.60515, 8.62279, -25.73289, 31.24579, 51.10698, 28.15894,
    15.69404, 31.4611, 40.24449
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["reporter_hdi"]], n = 30),
  c(
    0.8964, 0.76613, 0.8976, 0.8976, 0.6528, 0.87527, 0.5956, 0.65033,
    0.73693, 0.73693, 0.8806, 0.86293, 0.86293, 0.81747, 0.90367,
    0.90367, 0.7118, 0.81427, 0.7706, 0.85567, 0.85567, 0.72027,
    0.72027, 0.89533, 0.89533, 0.47053, 0.47053, 0.90607, 0.90607,
    0.90607
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["partner_hdi"]], n = 30),
  c(
    0.93607, 0.8976, 0.88153, 0, 0.79133, 0.8072, 0.82307, 0, 0.83293,
    0.44179, 0.8966, 0.79773, 0.7706, 0.81293, 0.88707, 0.79773,
    0.90607, 0.71827, 0, 0.82307, 0.90607, 0.773, 0.38127, 0.91773,
    0.7268, 0.91167, 0.70973, 0.5956, 0.8806, 0.85567
  ),
  tolerance = 1e-4
)
# Testing column names
expect_equal(
  names(output_19148),
  c(
    "reporter_countries", "partner_countries", "year", "vp_flow",
    "reporter_long", "reporter_lat", "partner_long", "partner_lat",
    "reporter_hdi", "partner_hdi"
  ),
  fixed = TRUE
)
# Testing column classes
expect_equal(
  xpectr::element_classes(output_19148),
  c(
    "character", "character", "numeric", "numeric", "numeric", "numeric",
    "numeric", "numeric", "numeric", "numeric"
  ),
  fixed = TRUE
)
# Testing column types
expect_equal(
  xpectr::element_types(output_19148),
  c(
    "character", "character", "double", "double", "double", "double",
    "double", "double", "double", "double"
  ),
  fixed = TRUE
)
# Testing dimensions
expect_equal(
  dim(output_19148),
  c(30621L, 10L)
)
# Testing group keys
expect_equal(
  colnames(dplyr::group_keys(output_19148)),
  character(0),
  fixed = TRUE
)
## Finished testing 'filter_countries_by_input_select_year(df, 2001)'       ####

# xpectr::gxs_selection("filter_countries_by_input_select_year(df, 'All years')")

## Testing 'filter_countries_by_input_select_year(df, 'All...'              ####
## Initially generated by xpectr
xpectr::set_test_seed(42)
# Assigning output
output_11846 <- filter_countries_by_input_select_year(df, "All years")
# Testing class
expect_equal(
  class(output_11846),
  c("tbl_df", "tbl", "data.frame"),
  fixed = TRUE
)
# Testing column values
expect_equal(
  xpectr::smpl(output_11846[["reporter_countries"]], n = 30),
  c(
    "Ukraine", "Estonia", "Saint Lucia", "Iran", "Cambodia", "United Arab Emirates",
    "Bulgaria", "Pakistan", "Moldova", "Cameroon", "United Republic of Tanzania",
    "Denmark", "Argentina", "Canada", "Ukraine", "Belgium", "Malaysia",
    "United Republic of Tanzania", "Switzerland", "Zambia", "Philippines",
    "India", "Hong Kong S.A.R.", "South Africa", "Pakistan", "Bolivia",
    "Russia", "Ghana", "New Zealand", "Italy"
  ),
  fixed = TRUE
)
expect_equal(
  xpectr::smpl(output_11846[["partner_countries"]], n = 30),
  c(
    "Ireland", "Marshall Islands", "Grenada", "Central African Republic",
    "Hong Kong S.A.R.", "Sri Lanka", "Dominican Republic", "South Africa",
    "Latvia", "Romania", "Lithuania", "Mauritania", "Guinea", "Slovakia",
    "Turkmenistan", "Brazil", "Uruguay", "Israel", "United States of America",
    "Democratic Republic of the Congo", "India", "Russia", "Macao S.A.R",
    "Ireland", "Unspecified Area", "United Kingdom", "Algeria",
    "Spain", "Netherlands", "Poland"
  ),
  fixed = TRUE
)
expect_equal(
  xpectr::smpl(output_11846[["reporter_long"]], n = 30),
  c(
    31.38326, 25.54249, -60.9697, 54.27407, 104.90694, 54.30017, 25.21553,
    69.33958, 28.45673, 12.73964, 34.8131, 10.02801, -65.17981,
    -98.30777, 31.38326, 4.64065, 109.69762, 34.8131, 8.20867, 27.77476,
    122.88393, 79.61198, 114.1138, 25.0839, 69.33958, -64.68539,
    96.68656, -1.21677, 171.48492, 12.07001
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_11846[["reporter_lat"]], n = 30),
  c(
    48.99657, 58.67193, 13.89479, 32.57503, 12.72005, 23.90528, 42.7689,
    29.94975, 47.19499, 5.6911, -6.27565, 55.98125, -35.38135, 61.36206,
    48.99657, 50.63982, 3.78987, -6.27565, 46.79786, -13.45824,
    11.77537, 22.88578, 22.39828, -29.00034, 29.94975, -16.70815,
    61.98052, 7.95346, -41.81114, 42.79663
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_11846[["reporter_hdi"]], n = 30),
  c(
    0.72333, 0.8356, 0.71593, 0.73693, 0.51407, 0.83293, 0.76613,
    0.511, 0.66, 0.4938, 0.47053, 0.90793, 0.7978, 0.8976, 0.72333,
    0.8964, 0.7572, 0.47053, 0.9182, 0.5166, 0.66013, 0.5626, 0.88707,
    0.6402, 0.511, 0.6422, 0.7706, 0.53547, 0.89507, 0.86293
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_11846[["partner_long"]], n = 30),
  c(
    -8.13794, 170.33976, -61.6822, 20.46827, 114.1138, 80.70108, -70.50569,
    25.0839, 24.91236, 24.97293, 23.88719, -10.3478, -10.94067,
    19.47905, 59.371, -53.09783, -56.01807, 35.00445, -112.46167,
    23.64396, 79.61198, 96.68656, 113.50932, -8.13794, NA, -2.86563,
    2.61732, -3.64755, 5.28145, 19.39013
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_11846[["partner_lat"]], n = 30),
  c(
    53.17545, 7.00376, 12.11725, 6.56823, 22.39828, 7.61267, 18.89433,
    -29.00034, 56.85085, 45.85243, 55.32611, 20.25737, 10.43622,
    48.70548, 39.11554, -10.78778, -32.79952, 31.4611, 45.67955,
    -2.87746, 22.88578, 61.98052, 22.22312, 53.17545, NA, 54.12387,
    28.15894, 40.24449, 52.10079, 52.1276
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_11846[["partner_hdi"]], n = 30),
  c(
    0.8994, 0, 0.73679, 0.3352, 0.88707, 0.733, 0.69173, 0.6402, 0.8072,
    0.77413, 0.81747, 0.47947, 0.39213, 0.81347, 0.68817, 0.71827,
    0.77087, 0.8806, 0.90607, 0.3886, 0.5626, 0.7706, 0, 0.8994,
    0, 0.89533, 0.70973, 0.85567, 0.90367, 0.82307
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_11846[["vp_flow"]], n = 30),
  c(
    0.78373, 1.50258, 2, 2.14102, 9.69564, 13.652, 39.39205, 72.85728,
    82.06866, 86.4059, 99.98094, 155.33664, 167.894, 271.94802,
    700.46909, 827.95419, 1482.22218, 1789.86529, 2289.00961, 9247.0956,
    10044.00301, 36490.19352, 37652.04787, 49112.6956, 78906.38717,
    85033.96324, 87995.33806, 104669.29459, 362475.05345, 618473.30933
  ),
  tolerance = 1e-4
)
# Testing column names
expect_equal(
  names(output_11846),
  c(
    "reporter_countries", "partner_countries", "reporter_long", "reporter_lat",
    "reporter_hdi", "partner_long", "partner_lat", "partner_hdi",
    "vp_flow"
  ),
  fixed = TRUE
)
# Testing column classes
expect_equal(
  xpectr::element_classes(output_11846),
  c(
    "character", "character", "numeric", "numeric", "numeric", "numeric",
    "numeric", "numeric", "numeric"
  ),
  fixed = TRUE
)
# Testing column types
expect_equal(
  xpectr::element_types(output_11846),
  c(
    "character", "character", "double", "double", "double", "double",
    "double", "double", "double"
  ),
  fixed = TRUE
)
# Testing dimensions
expect_equal(
  dim(output_11846),
  c(11505L, 9L)
)
# Testing group keys
expect_equal(
  colnames(dplyr::group_keys(output_11846)),
  character(0),
  fixed = TRUE
)
## Finished testing 'filter_countries_by_input_select_year(df, 'All...'     ####
