context("Testing `test-distinct_countries_for_dt.R()`")

pkg_data <-
  system.file("extdata", "virtual-pollinators-flow.qs", package = "vbpflow")

df <-
  qread(pkg_data)

origin <- "Brazil"

destination <- c("China", "Japan", "Italy")

year <- 2004

# xpectr::gxs_selection("distinct_countries_for_dt(df, origin, destination, year)")

## Testing 'distinct_countries_for_dt(df, origin, destinat...'              ####
## Initially generated by xpectr
xpectr::set_test_seed(42)
# Assigning output
output_19148 <- distinct_countries_for_dt(df, origin, destination, year)
# Testing class
expect_equal(
  class(output_19148),
  c("tbl_df", "tbl", "data.frame"),
  fixed = TRUE
)
# Testing column values
expect_equal(
  output_19148[["Exporting country"]],
  c("Brazil", "Brazil", "Brazil"),
  fixed = TRUE
)
expect_equal(
  output_19148[["Importing country"]],
  c("China", "Italy", "Japan"),
  fixed = TRUE
)
expect_equal(
  output_19148[["Year"]],
  c(2004, 2004, 2004),
  tolerance = 1e-4
)
expect_equal(
  output_19148[["Virtual Biotic Pollination Flow (tons)"]],
  c(1436631.6, 236392.1, 105636.3),
  tolerance = 1e-4
)
# Testing column names
expect_equal(
  names(output_19148),
  c("Exporting country", "Importing country", "Year", "Virtual Biotic Pollination Flow (tons)"),
  fixed = TRUE
)
# Testing column classes
expect_equal(
  xpectr::element_classes(output_19148),
  c("character", "character", "numeric", "numeric"),
  fixed = TRUE
)
# Testing column types
expect_equal(
  xpectr::element_types(output_19148),
  c("character", "character", "double", "double"),
  fixed = TRUE
)
# Testing dimensions
expect_equal(
  dim(output_19148),
  3:4
)
# Testing group keys
expect_equal(
  colnames(dplyr::group_keys(output_19148)),
  character(0),
  fixed = TRUE
)
## Finished testing 'distinct_countries_for_dt(df, origin, destinat...'     ####

# xpectr::gxs_selection("distinct_countries_for_dt(df, origin, destination, 'All years')")

## Testing 'distinct_countries_for_dt(df, origin, destinat...'              ####
## Initially generated by xpectr
xpectr::set_test_seed(42)
# Assigning output
output_19148 <- distinct_countries_for_dt(df, origin, destination, "All years")
# Testing class
expect_equal(
  class(output_19148),
  c("tbl_df", "tbl", "data.frame"),
  fixed = TRUE
)
# Testing column values
expect_equal(
  output_19148[["Exporting country"]],
  c("Brazil", "Brazil", "Brazil"),
  fixed = TRUE
)
expect_equal(
  output_19148[["Importing country"]],
  c("China", "Italy", "Japan"),
  fixed = TRUE
)
expect_equal(
  output_19148[["Virtual Biotic Pollination Flow (tons)"]],
  c(54408623.3, 2929463.1, 2132563.1),
  tolerance = 1e-4
)
# Testing column names
expect_equal(
  names(output_19148),
  c("Exporting country", "Importing country", "Virtual Biotic Pollination Flow (tons)"),
  fixed = TRUE
)
# Testing column classes
expect_equal(
  xpectr::element_classes(output_19148),
  c("character", "character", "numeric"),
  fixed = TRUE
)
# Testing column types
expect_equal(
  xpectr::element_types(output_19148),
  c("character", "character", "double"),
  fixed = TRUE
)
# Testing dimensions
expect_equal(
  dim(output_19148),
  c(3L, 3L)
)
# Testing group keys
expect_equal(
  colnames(dplyr::group_keys(output_19148)),
  character(0),
  fixed = TRUE
)
## Finished testing 'distinct_countries_for_dt(df, origin, destinat...'     ####
