context("Testing `summarise_vp_flow_all_years()`")

# df <- read_vp_flow_data()

pkg_data <- 
  system.file("extdata", "virtual-pollinators-flow.qs", package="vbpflow")

df <- 
  qread(pkg_data) %>%
  filter(item_code != 0) %>%
  .[.$reporter_countries != .$partner_countries, ]


# gxs_selection("summarise_vp_flow_all_years(df)")

## Testing 'summarise_vp_flow_all_years(df)'                                ####
## Initially generated by xpectr
xpectr::set_test_seed(42)
# Assigning output
output_19148 <- summarise_vp_flow_all_years(df)
# Testing class
expect_equal(
  class(output_19148),
  c("tbl_df", "tbl", "data.frame"),
  fixed = TRUE)
# Testing column values
expect_equal(
  xpectr::smpl(output_19148[["reporter_countries"]], n = 30),
  c("Bulgaria", "Saint Vincent and the Grenadines", "Chile", "Guyana", 
    "Lithuania", "Syria", "Ukraine", "Paraguay", "Montenegro", "Cyprus", 
    "Colombia", "Saint Lucia", "Honduras", "Taiwan", "United States of America", 
    "Afghanistan", "Mexico", "Macedonia", "Malaysia", "South Africa", 
    "Ivory Coast", "United Kingdom", "Albania", "China", "Hungary", 
    "Portugal", "Thailand", "Lithuania", "Philippines", "Chile"),
  fixed = TRUE)
expect_equal(
  xpectr::smpl(output_19148[["partner_countries"]], n = 30),
  c("Azerbaijan", "Germany", "Afghanistan", "Bosnia and Herzegovina", 
    "Republic of Serbia", "Bulgaria", "Serbia and Montenegro", "Sweden", 
    "Russia", "Malaysia", "Macao S.A.R", "Unspecified Area", "Chile", 
    "Netherlands", "Mali", "Iraq", "Denmark", "Ukraine", "Kiribati", 
    "Gabon", "Portugal", "Italy", "Unspecified Area", "Turkey", 
    "Romania", "Cape Verde", "Malaysia", "Germany", "China", "United Kingdom"),
  fixed = TRUE)
expect_equal(
  xpectr::smpl(output_19148[["reporter_long"]], n = 30),
  c(25.21553, -61.2013, -71.38256, -58.98202, 23.88719, 38.50788,
31.38326, -58.40014, 19.23884, 33.006, -73.08115, -60.9697,
-86.61517, 120.95427, -112.46167, 66.00473, -102.52345, 21.68211,
109.69762, 25.0839, -5.56922, -2.86563, 20.04983, 103.81907,
19.39559, -8.50104, 101.00288, 23.88719, 122.88393, -71.38256),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(output_19148[["reporter_lat"]], n = 30),
  c(42.7689, 13.22472, -37.73071, 4.79378, 55.32611, 35.02547, 48.99657,
-23.22824, 42.7889, 34.91667, 3.91383, 13.89479, 14.82688, 23.75399,
45.67955, 33.83523, 23.94754, 41.59531, 3.78987, -29.00034,
7.62843, 54.12387, 41.14245, 36.56177, 47.16278, 39.59551, 15.11816,
55.32611, 11.77537, -37.73071),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(output_19148[["reporter_hdi"]], n = 30),
  c(0.76613, 0.7056, 0.80093, 0.6252, 0.81747, 0.6152, 0.72333, 0.6644,
0.78177, 0.8414, 0.70193, 0.71593, 0.58713, 0, 0.90607, 0.44179,
0.7386, 0.71793, 0.7572, 0.6402, 0.43147, 0.89533, 0.72727,
0.679, 0.81293, 0.81427, 0.70667, 0.81747, 0.66013, 0.80093),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(output_19148[["partner_long"]], n = 30),
  c(47.546, 10.38578, 66.00473, 17.76877, 20.78958, 25.21553, 20.85498,
16.74558, 96.68656, 109.69762, 113.50932, NA, -71.38256, 5.28145,
-3.54269, 43.74353, 10.02801, 31.38326, -45.61111, 11.78863,
-8.50104, 12.07001, NA, 35.16895, 24.97293, -23.95989, 109.69762,
10.38578, 103.81907, -2.86563),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(output_19148[["partner_lat"]], n = 30),
  c(40.28827, 51.10698, 33.83523, 44.1745, 44.2215, 42.7689, 43.55966,
62.77967, 61.98052, 3.78987, 22.22312, NA, -37.73071, 52.10079,
17.34582, 33.03971, 55.98125, 48.99657, 0.86002, -0.5866, 39.59551,
42.79663, NA, 39.0616, 45.85243, 15.95523, 3.78987, 51.10698,
36.56177, 54.12387),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(output_19148[["partner_hdi"]], n = 30),
  c(0.7124, 0.91167, 0.44179, 0.7152, 0, 0.76613, 0.7516, 0.90613,
0.7706, 0.7572, 0, 0, 0.80093, 0.90367, 0.37967, 0.64127, 0.90793,
0.72333, 0.5874, 0.66027, 0.81427, 0.86293, 0, 0.72027, 0.77413,
0.617, 0.7572, 0.91167, 0.679, 0.89533),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(output_19148[["vp_flow"]], n = 30),
  c(0.8235, 1.6, 2.16947, 2.28253, 9.92017, 13.77538, 40.28622, 73.22256,
83.3152, 87.79841, 99.59968, 159.60498, 169.30723, 270.08786,
691.41875, 829.14061, 1473.6708, 1739.13357, 2190.27191, 8263.65702,
8701.00906, 28910.44348, 29613.55738, 38064.48001, 57872.05507,
63192.10252, 66364.19154, 77982.77476, 272362.16075, 485120.71555),
  tolerance = 1e-4)
# Testing column names
expect_equal(
  names(output_19148),
  c("reporter_countries", "partner_countries", "reporter_long", "reporter_lat", 
    "reporter_hdi", "partner_long", "partner_lat", "partner_hdi", 
    "vp_flow"),
  fixed = TRUE)
# Testing column classes
expect_equal(
  xpectr::element_classes(output_19148),
  c("character", "character", "numeric", "numeric", "numeric", "numeric", 
    "numeric", "numeric", "numeric"),
  fixed = TRUE)
# Testing column types
expect_equal(
  xpectr::element_types(output_19148),
  c("character", "character", "double", "double", "double", "double", 
    "double", "double", "double"),
  fixed = TRUE)
# Testing dimensions
expect_equal(
  dim(output_19148),
  c(11786L, 9L))
# Testing group keys
expect_equal(
  colnames(dplyr::group_keys(output_19148)),
  character(0),
  fixed = TRUE)
## Finished testing 'summarise_vp_flow_all_years(df)'                       ####

