context("Testing `filter_countries_by_input_select_countries()`")

pkg_data <-
  system.file("extdata", "virtual-pollinators-flow.qs", package = "vbpflow")

df <-
  qread(pkg_data)

# xpectr::gxs_selection("filter_countries_by_input_select_countries(df, 'Brazil', 'China')")

## Testing 'filter_countries_by_input_select_countries(df,...'              ####
## Initially generated by xpectr
xpectr::set_test_seed(42)
# Assigning output
output_19148 <- filter_countries_by_input_select_countries(df, "Brazil", "China")
# Testing class
expect_equal(
  class(output_19148),
  c("tbl_df", "tbl", "data.frame"),
  fixed = TRUE
)
# Testing column values
expect_equal(
  output_19148[["reporter_countries"]],
  c(
    "Brazil", "Brazil", "Brazil", "Brazil", "Brazil", "Brazil", "Brazil",
    "Brazil", "Brazil", "Brazil", "Brazil", "Brazil", "Brazil",
    "Brazil", "Brazil"
  ),
  fixed = TRUE
)
expect_equal(
  output_19148[["partner_countries"]],
  c(
    "China", "China", "China", "China", "China", "China", "China",
    "China", "China", "China", "China", "China", "China", "China",
    "China"
  ),
  fixed = TRUE
)
expect_equal(
  output_19148[["reporter_long"]],
  c(
    -53.09783, -53.09783, -53.09783, -53.09783, -53.09783, -53.09783,
    -53.09783, -53.09783, -53.09783, -53.09783, -53.09783, -53.09783,
    -53.09783, -53.09783, -53.09783
  ),
  tolerance = 1e-4
)
expect_equal(
  output_19148[["reporter_lat"]],
  c(
    -10.78778, -10.78778, -10.78778, -10.78778, -10.78778, -10.78778,
    -10.78778, -10.78778, -10.78778, -10.78778, -10.78778, -10.78778,
    -10.78778, -10.78778, -10.78778
  ),
  tolerance = 1e-4
)
expect_equal(
  output_19148[["reporter_hdi"]],
  c(
    0.71827, 0.71827, 0.71827, 0.71827, 0.71827, 0.71827, 0.71827,
    0.71827, 0.71827, 0.71827, 0.71827, 0.71827, 0.71827, 0.71827,
    0.71827
  ),
  tolerance = 1e-4
)
expect_equal(
  output_19148[["partner_long"]],
  c(
    103.81907, 103.81907, 103.81907, 103.81907, 103.81907, 103.81907,
    103.81907, 103.81907, 103.81907, 103.81907, 103.81907, 103.81907,
    103.81907, 103.81907, 103.81907
  ),
  tolerance = 1e-4
)
expect_equal(
  output_19148[["partner_lat"]],
  c(
    36.56177, 36.56177, 36.56177, 36.56177, 36.56177, 36.56177, 36.56177,
    36.56177, 36.56177, 36.56177, 36.56177, 36.56177, 36.56177,
    36.56177, 36.56177
  ),
  tolerance = 1e-4
)
expect_equal(
  output_19148[["partner_hdi"]],
  c(
    0.679, 0.679, 0.679, 0.679, 0.679, 0.679, 0.679, 0.679, 0.679,
    0.679, 0.679, 0.679, 0.679, 0.679, 0.679
  ),
  tolerance = 1e-4
)
expect_equal(
  output_19148[["year"]],
  c(
    2001, 2002, 2004, 2003, 2005, 2007, 2006, 2008, 2009, 2010, 2011,
    2012, 2013, 2014, 2015
  ),
  tolerance = 1e-4
)
expect_equal(
  output_19148[["vp_flow"]],
  c(
    698634.33037, 967416.637, 1436631.5906, 1446457.43181, 1646592.65083,
    2298670.12031, 2407987.51117, 2740284.39513, 3602419.13199,
    3672273.13817, 4976620.92178, 5108184.16492, 7172948.26091,
    7233291.33768, 9000211.72187
  ),
  tolerance = 1e-4
)
# Testing column names
expect_equal(
  names(output_19148),
  c(
    "reporter_countries", "partner_countries", "reporter_long", "reporter_lat",
    "reporter_hdi", "partner_long", "partner_lat", "partner_hdi",
    "year", "vp_flow"
  ),
  fixed = TRUE
)
# Testing column classes
expect_equal(
  xpectr::element_classes(output_19148),
  c(
    "character", "character", "numeric", "numeric", "numeric", "numeric",
    "numeric", "numeric", "numeric", "numeric"
  ),
  fixed = TRUE
)
# Testing column types
expect_equal(
  xpectr::element_types(output_19148),
  c(
    "character", "character", "double", "double", "double", "double",
    "double", "double", "double", "double"
  ),
  fixed = TRUE
)
# Testing dimensions
expect_equal(
  dim(output_19148),
  c(15L, 10L)
)
# Testing group keys
expect_equal(
  colnames(dplyr::group_keys(output_19148)),
  character(0),
  fixed = TRUE
)
## Finished testing 'filter_countries_by_input_select_countries(df,...'     ####
