context("Testing `filter_countries_by_input_select_year()`")

pkg_data <-
  system.file("extdata", "virtual-pollinators-flow.qs", package = "vbpflow")

df <-
  qread(pkg_data) %>%
  .[.$reporter_countries != .$partner_countries, ]

# xpectr::gxs_selection("filter_countries_by_input_select_year(df, 2001)")

## Testing 'filter_countries_by_input_select_year(df, 2001)'                ####
## Initially generated by xpectr
xpectr::set_test_seed(42)
# Assigning output
output_19148 <- filter_countries_by_input_select_year(df, 2001)
# Testing class
expect_equal(
  class(output_19148),
  c("spec_tbl_df", "tbl_df", "tbl", "data.frame"),
  fixed = TRUE
)
# Testing column values
expect_equal(
  xpectr::smpl(output_19148[["reporter_countries"]], n = 30),
  c(
    "Belgium", "Bulgaria", "Canada", "Canada", "Egypt", "France",
    "Guatemala", "Indonesia", "Iran", "Iran", "Israel", "Italy",
    "Italy", "Lithuania", "Netherlands", "Netherlands", "Peru",
    "Portugal", "Russia", "Spain", "Spain", "Turkey", "Turkey",
    "United Kingdom", "United Kingdom", "United Republic of Tanzania",
    "United Republic of Tanzania", "United States of America", "United States of America",
    "United States of America"
  ),
  fixed = TRUE
)
expect_equal(
  xpectr::smpl(output_19148[["partner_countries"]], n = 30),
  c(
    "Norway", "Canada", "Japan", "Taiwan", "Kuwait", "Latvia", "Poland",
    "Somalia", "United Arab Emirates", "Afghanistan", "Finland",
    "Croatia", "Russia", "Hungary", "Hong Kong S.A.R.", "Croatia",
    "United States of America", "Brazil", "Unspecified Area", "Poland",
    "United States of America", "Oman", "Ethiopia", "Australia",
    "Jordan", "Germany", "Algeria", "Guatemala", "Israel", "Spain"
  ),
  fixed = TRUE
)
expect_equal(
  xpectr::smpl(output_19148[["year"]], n = 30),
  c(
    2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001,
    2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001,
    2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["vp_flow"]], n = 30),
  c(
    8.3243, 1.72506, 0.71047, 8.8098, 0.01243, 0.18932, 4.84283, 22.37298,
    330.94157, 198.42296, 3.18766, 48.99208, 542.6461, 45.93194,
    30.39562, 2.76357, 22.10943, 395.12107, 0.0287, 76.09733, 5.5836,
    13.87149, 24.74746, 1.90182, 0.12679, 0.46709, 6.80019, 1.51406,
    13.64707, 283.32137
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["reporter_long"]], n = 30),
  c(
    4.64065, 25.21553, -98.30777, -98.30777, 29.8619, -2.76173, -90.36482,
    117.24011, 54.27407, 54.27407, 35.00445, 12.07001, 12.07001,
    23.88719, 5.28145, 5.28145, -74.38243, -8.50104, 96.68656, -3.64755,
    -3.64755, 35.16895, 35.16895, -2.86563, -2.86563, 34.8131, 34.8131,
    -112.46167, -112.46167, -112.46167
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["reporter_lat"]], n = 30),
  c(
    50.63982, 42.7689, 61.36206, 61.36206, 26.49593, 42.17344, 15.69404,
    -2.21505, 32.57503, 32.57503, 31.4611, 42.79663, 42.79663, 55.32611,
    52.10079, 52.10079, -9.1528, 39.59551, 61.98052, 40.24449, 40.24449,
    39.0616, 39.0616, 54.12387, 54.12387, -6.27565, -6.27565, 45.67955,
    45.67955, 45.67955
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["partner_long"]], n = 30),
  c(
    15.34835, -98.30777, 138.0309, 120.95427, 47.587, 24.91236, 19.39013,
    45.70714, 54.30017, 66.00473, 26.27467, 16.40413, 96.68656,
    19.39559, 114.1138, 16.40413, -112.46167, -53.09783, NA, 19.39013,
    -112.46167, 56.09166, 39.6008, 134.491, 36.77136, 10.38578,
    2.61732, -90.36482, 35.00445, -3.64755
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["partner_lat"]], n = 30),
  c(
    68.75016, 61.36206, 37.5923, 23.75399, 29.33431, 56.85085, 52.1276,
    4.75063, 23.90528, 33.83523, 64.49885, 45.08048, 61.98052, 47.16278,
    22.39828, 45.08048, 45.67955, -10.78778, NA, 52.1276, 45.67955,
    20.60515, 8.62279, -25.73289, 31.24579, 51.10698, 28.15894,
    15.69404, 31.4611, 40.24449
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["reporter_hdi"]], n = 30),
  c(
    0.8964, 0.76613, 0.8976, 0.8976, 0.6528, 0.87527, 0.5956, 0.65033,
    0.73693, 0.73693, 0.8806, 0.86293, 0.86293, 0.81747, 0.90367,
    0.90367, 0.7118, 0.81427, 0.7706, 0.85567, 0.85567, 0.72027,
    0.72027, 0.89533, 0.89533, 0.47053, 0.47053, 0.90607, 0.90607,
    0.90607
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["partner_hdi"]], n = 30),
  c(
    0.93607, 0.8976, 0.88153, 0, 0.79133, 0.8072, 0.82307, 0, 0.83293,
    0.44179, 0.8966, 0.79773, 0.7706, 0.81293, 0.88707, 0.79773,
    0.90607, 0.71827, 0, 0.82307, 0.90607, 0.773, 0.38127, 0.91773,
    0.7268, 0.91167, 0.70973, 0.5956, 0.8806, 0.85567
  ),
  tolerance = 1e-4
)
# Testing column names
expect_equal(
  names(output_19148),
  c(
    "reporter_countries", "partner_countries", "year", "vp_flow",
    "reporter_long", "reporter_lat", "partner_long", "partner_lat",
    "reporter_hdi", "partner_hdi"
  ),
  fixed = TRUE
)
# Testing column classes
expect_equal(
  xpectr::element_classes(output_19148),
  c(
    "character", "character", "numeric", "numeric", "numeric", "numeric",
    "numeric", "numeric", "numeric", "numeric"
  ),
  fixed = TRUE
)
# Testing column types
expect_equal(
  xpectr::element_types(output_19148),
  c(
    "character", "character", "double", "double", "double", "double",
    "double", "double", "double", "double"
  ),
  fixed = TRUE
)
# Testing dimensions
expect_equal(
  dim(output_19148),
  c(30621L, 10L)
)
# Testing group keys
expect_equal(
  colnames(dplyr::group_keys(output_19148)),
  character(0),
  fixed = TRUE
)
## Finished testing 'filter_countries_by_input_select_year(df, 2001)'       ####
