context("Testing `distinct_countries()`")

pkg_data <-
  system.file("extdata", "virtual-pollinators-flow.qs", package = "vbpflow")

df <-
  qread(pkg_data) %>%
  .[.$reporter_countries != .$partner_countries, ]

# xpectr::gxs_selection("distinct_countries(df)")

## Testing 'distinct_countries(df)'                                         ####
## Initially generated by xpectr
xpectr::set_test_seed(42)
# Assigning output
output_19148 <- distinct_countries(df)
# Testing class
expect_equal(
  class(output_19148),
  c("tbl_df", "tbl", "data.frame"),
  fixed = TRUE
)
# Testing column values
expect_equal(
  xpectr::smpl(output_19148[["reporter_countries"]], n = 30),
  c(
    "Croatia", "Japan", "Canada", "Canada", "Argentina", "Nepal",
    "Brazil", "Indonesia", "China", "Canada", "Netherlands", "Japan",
    "Brazil", "Pakistan", "Spain", "Netherlands", "Portugal", "Malaysia",
    "Guatemala", "Argentina", "Malaysia", "Malaysia", "Australia",
    "Guatemala", "United States of America", "Chile", "New Zealand",
    "Malaysia", "China", "China"
  ),
  fixed = TRUE
)
expect_equal(
  xpectr::smpl(output_19148[["partner_countries"]], n = 30),
  c(
    "Switzerland", "Sweden", "Lithuania", "Bulgaria", "Burundi", "United Arab Emirates",
    "Netherlands Antilles", "Norway", "Libya", "Czech Republic",
    "Haiti", "Philippines", "Cape Verde", "Indonesia", "Cape Verde",
    "Republic of Serbia", "Guinea Bissau", "Gambia", "Norway", "Australia",
    "Denmark", "Jordan", "India", "Mexico", "Italy", "France", "Hong Kong S.A.R.",
    "Nigeria", "India", "Indonesia"
  ),
  fixed = TRUE
)
expect_equal(
  xpectr::smpl(output_19148[["reporter_long"]], n = 30),
  c(
    16.40413, 138.0309, -98.30777, -98.30777, -65.17981, 83.91583,
    -53.09783, 117.24011, 103.81907, -98.30777, 5.28145, 138.0309,
    -53.09783, 69.33958, -3.64755, 5.28145, -8.50104, 109.69762,
    -90.36482, -65.17981, 109.69762, 109.69762, 134.491, -90.36482,
    -112.46167, -71.38256, 171.48492, 109.69762, 103.81907, 103.81907
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["reporter_lat"]], n = 30),
  c(
    45.08048, 37.5923, 61.36206, 61.36206, -35.38135, 28.24891, -10.78778,
    -2.21505, 36.56177, 61.36206, 52.10079, 37.5923, -10.78778,
    29.94975, 40.24449, 52.10079, 39.59551, 3.78987, 15.69404, -35.38135,
    3.78987, 3.78987, -25.73289, 15.69404, 45.67955, -37.73071,
    -41.81114, 3.78987, 36.56177, 36.56177
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["reporter_hdi"]], n = 30),
  c(
    0.79773, 0.88153, 0.8976, 0.8976, 0.7978, 0.50633, 0.71827, 0.65033,
    0.679, 0.8976, 0.90367, 0.88153, 0.71827, 0.511, 0.85567, 0.90367,
    0.81427, 0.7572, 0.5956, 0.7978, 0.7572, 0.7572, 0.91773, 0.5956,
    0.90607, 0.80093, 0.89507, 0.7572, 0.679, 0.679
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["partner_long"]], n = 30),
  c(
    8.20867, 16.74558, 23.88719, 25.21553, 29.87512, 54.30017, -65.50987,
    15.34835, 18.00866, 15.3124, -72.68528, 122.88393, -23.95989,
    117.24011, -23.95989, 20.78958, -14.94972, -15.39601, 15.34835,
    134.491, 10.02801, 36.77136, 79.61198, -102.52345, 12.07001,
    -2.76173, 114.1138, 8.08944, 79.61198, 117.24011
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["partner_lat"]], n = 30),
  c(
    46.79786, 62.77967, 55.32611, 42.7689, -3.3594, 23.90528, 14.58622,
    68.75016, 27.03094, 49.73341, 18.93503, 11.77537, 15.95523,
    -2.21505, 15.95523, 44.2215, 12.04745, 13.44965, 68.75016, -25.73289,
    55.98125, 31.24579, 22.88578, 23.94754, 42.79663, 42.17344,
    22.39828, 9.59411, 22.88578, -2.21505
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["partner_hdi"]], n = 30),
  c(
    0.9182, 0.90613, 0.81747, 0.76613, 0.3674, 0.83293, 0, 0.93607,
    0.7342, 0.8488, 0.46633, 0.66013, 0.617, 0.65033, 0.617, 0,
    0.42518, 0.4288, 0.93607, 0.91773, 0.90793, 0.7268, 0.5626,
    0.7386, 0.86293, 0.87527, 0.88707, 0.48915, 0.5626, 0.65033
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["year"]], n = 30),
  c(
    2001, 2004, 2008, 2011, 2005, 2011, 2009, 2010, 2004, 2014, 2002,
    2003, 2010, 2011, 2011, 2007, 2002, 2003, 2011, 2001, 2010,
    2006, 2002, 2015, 2005, 2010, 2015, 2011, 2014, 2007
  ),
  tolerance = 1e-4
)
expect_equal(
  xpectr::smpl(output_19148[["vp_flow"]], n = 30),
  c(
    0.57169, 1.06177, 1.42391, 1.51207, 6.6685, 9.29549, 25.20171,
    42.39684, 46.72369, 48.75845, 55.32306, 81.00686, 85.08064,
    124.87347, 277.0499, 320.92104, 534.49887, 629.24247, 769.70204,
    2436.31719, 2611.42993, 7409.42229, 7588.20696, 8975.36002,
    13574.098, 14396.41741, 15261.62499, 18036.32163, 50315.06854,
    105476.3844
  ),
  tolerance = 1e-4
)
# Testing column names
expect_equal(
  names(output_19148),
  c(
    "reporter_countries", "partner_countries", "reporter_long", "reporter_lat",
    "reporter_hdi", "partner_long", "partner_lat", "partner_hdi",
    "year", "vp_flow"
  ),
  fixed = TRUE
)
# Testing column classes
expect_equal(
  xpectr::element_classes(output_19148),
  c(
    "character", "character", "numeric", "numeric", "numeric", "numeric",
    "numeric", "numeric", "numeric", "numeric"
  ),
  fixed = TRUE
)
# Testing column types
expect_equal(
  xpectr::element_types(output_19148),
  c(
    "character", "character", "double", "double", "double", "double",
    "double", "double", "double", "double"
  ),
  fixed = TRUE
)
# Testing dimensions
expect_equal(
  dim(output_19148),
  c(88483L, 10L)
)
# Testing group keys
expect_equal(
  colnames(dplyr::group_keys(output_19148)),
  character(0),
  fixed = TRUE
)
## Finished testing 'distinct_countries(df)'                                ####
