context("Testing `test-distinct_countries_with_item.R()`")

pkg_data <- 
  system.file("extdata", "virtual-pollinators-flow.qs", package="vbpflow")

df <- 
  qread(pkg_data) %>%
  filter(item_code != 0) %>%
  .[.$reporter_countries != .$partner_countries, ]

origin <- "Brazil"

destination <- c("China", "Japan", "Italy")

year <- 2004

# distinct_countries_with_item(df, origin, destination, year)

# xpectr::gxs_selection("distinct_countries_with_item(df, origin, destination, year)")

## Testing 'distinct_countries_with_item(df, origin, desti...'              ####
## Initially generated by xpectr
xpectr::set_test_seed(42)
# Assigning output
output_19370 <- distinct_countries_with_item(df, origin, destination, year)
# Testing class
expect_equal(
  class(output_19370),
  c("tbl_df", "tbl", "data.frame"),
  fixed = TRUE)
# Testing column values
expect_equal(
  xpectr::smpl(output_19370[["Exporting country"]], n = 30),
  c("Brazil", "Brazil", "Brazil", "Brazil", "Brazil", "Brazil", "Brazil", 
    "Brazil", "Brazil", "Brazil", "Brazil", "Brazil", "Brazil", 
    "Brazil", "Brazil", "Brazil", "Brazil", "Brazil", "Brazil", 
    "Brazil", "Brazil", "Brazil", "Brazil", "Brazil", "Brazil", 
    "Brazil", "Brazil", "Brazil", "Brazil", "Brazil"),
  fixed = TRUE)
expect_equal(
  xpectr::smpl(output_19370[["Importing country"]], n = 30),
  c("China", "Italy", "Italy", "Italy", "Italy", "Italy", "Japan", 
    "Italy", "Italy", "Italy", "Japan", "China", "Japan", "Italy", 
    "Italy", "Japan", "Italy", "Italy", "Italy", "Italy", "China", 
    "Japan", "Italy", "China", "Italy", "Japan", "Italy", "Italy", 
    "Italy", "Japan"),
  fixed = TRUE)
expect_equal(
  xpectr::smpl(output_19370[["Item"]], n = 30),
  c("Oil, soybean", "Soybeans", "Coffee, green", "Cottonseed", "Apples", 
    "Melons, other (inc.cantaloupes)", "Cottonseed", "Oil, soybean", 
    "Oil, groundnut", "Groundnuts, shelled", "Cocoa, beans", "Coffee, green", 
    "Beans, dry", "Watermelons", "Brazil nuts, shelled", "Oil, cottonseed", 
    "Papayas", "Coconuts", "Lemons and limes", "Tangerines, mandarins, clementines, satsumas", 
    "Apples", "Beans, green", "Beans, dry", "Chillies and peppers, dry", 
    "Avocados", "Oil, groundnut", "Strawberries", "Chillies and peppers, green", 
    "Persimmons", "Chillies and peppers, green"),
  fixed = TRUE)
expect_equal(
  xpectr::smpl(output_19370[["Year"]], n = 30),
  c(2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004,
2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004,
2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004),
  tolerance = 1e-4)
expect_equal(
  xpectr::smpl(output_19370[["Virtual Biotic Pollination Flow (tons)"]], n = 30),
  c(528569.1, 103245.9, 17166.7, 3584.6, 2368.5, 1445.1, 621.3, 580.1,
259.8, 73.3, 63.7, 55.7, 41, 23.2, 20, 18.6, 17.3, 10.7, 9.8,
9.7, 6.5, 2.4, 1.2, 0.8, 0.6, 0.4, 0.4, 0.2, 0, 0),
  tolerance = 1e-4)
# Testing column names
expect_equal(
  names(output_19370),
  c("Exporting country", "Importing country", "Item", "Year", "Virtual Biotic Pollination Flow (tons)"),
  fixed = TRUE)
# Testing column classes
expect_equal(
  xpectr::element_classes(output_19370),
  c("character", "character", "character", "numeric", "numeric"),
  fixed = TRUE)
# Testing column types
expect_equal(
  xpectr::element_types(output_19370),
  c("character", "character", "character", "double", "double"),
  fixed = TRUE)
# Testing dimensions
expect_equal(
  dim(output_19370),
  c(38L, 5L))
# Testing group keys
expect_equal(
  colnames(dplyr::group_keys(output_19370)),
  character(0),
  fixed = TRUE)
## Finished testing 'distinct_countries_with_item(df, origin, desti...'     ####

